<footer id="footer" class="wrapper">
  <div class="inner">
    <div id="footer-copyright">
      &copy; {{ moment(Date.now()).year() }} <span style="font-weight: bold;">{{ config.author }}</span><br>
      Powered by <a href="https://hexo.io" target="_blank">Hexo.</a>
    </div>
    <div id="footer-links">
      <a href="/about/" class="footer-link"><i class="fa fa-envelope"></i></a>
    </div>
  </div>
</footer>
